### ISSUE TITLE
Target selection during edge creation/reconnect not working reliably

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp-client#28]
During edge creation/reconnect it's sometimes possible that the mouse cursors moves on top of the feedback edge end (e.g. if Arrow heads are used). This will break the target selection (because and edge cannot connect to itself and is therefore no valid target)

![transitions_bug](https://user-images.githubusercontent.com/2311075/72815687-5135cd80-3c67-11ea-8cfd-b4aa5f6666c0.gif)

(This also occurs when zoomed out but is better to demonstrate with a higher zoom level)

(could be related to https://github.com/eclipsesource/ecore-glsp/issues/93)

**Comment by planger** [comment]
I think this may be caused by paths with negative values, such as `d="M -2.5,0 L 8,-4 L 8,4 Z"` because they'll overlap beyond the anchor point and therefore will be below the cursor.
Ideally we should ignore the feedback edge as a target, but I guess it can also be circumvented by changing the SVG so that it never overlaps the anchor point.

**Comment by planger** [comment]
Oh, another idea (workaround) might be to position the anchor element for the feedback edge a few pixels back (to the source of the edge) to give more room for paths reaching beyond the anchor. But still, this is more like a workaround.

**Comment by tortmayr** [comment]
We should find a general solution for this, because there are other possible scenarios that can cause the same problem (like overlapping Popups or UI extensions).

**Comment by tortmayr** [comment]
Preferably a mechanism to ignore certain items as targets and (in case of ignore) check if there is another suitable target at the position

**Comment by tortmayr** [comment]
This is fixed with #29. Via snapping to the border it's no longer possible to accidentally selected the feedback edge
