### ISSUE TITLE
ResizeTool is not aware of MovementRestrictors

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp-client#8]
see https://github.com/eclipsesource/graphical-lsp/issues/391

**Comment by tortmayr** [comment]
Fixed with #27

**Comment by planger** [comment]
@tortmayr Is this really fixed? I thought #27 only addressed the move-part but not the resize part? I think the resize handles don't respect the movement restrictors yet, do they?
I might be missing something though. Thanks!

**Comment by tortmayr** [comment]
Yes this is fixed: ![prove](https://user-images.githubusercontent.com/2311075/74018914-03270680-4997-11ea-85cb-5a6499a16857.gif)

**Comment by tortmayr** [comment]
Maybe you were thinking of the snapping of the resize tool?. This is still missing and tracked with #34

**Comment by planger** [comment]
Ah ok, yes, I meant the issue that is tracked now in #34. :+1:
